image: nixos/23.05
oauth: pages.sr.ht/PAGES:RW
packages:
- nixos.hut
- nixos.emanote
sources:
  - https://git.sr.ht/~j14i/zettels
environment:
  site: j14i.srht.site
  NIX_CONFIG: "experimental-features = nix-command flakes"
tasks:
- build: |
    cd zettels
    emanote -L . gen ../$site
- package: |
    cd $site
    tar -cvz . > ../site.tar.gz
- upload: |
    hut pages publish -d $site site.tar.gz
